### PR TITLE
Adds computed property to encrypt and decrypt text example

### PR DESCRIPTION
**Pull request by franciscoemanuel**
Adds a encrypt/decrypt message example for computed properties.

### CODE REVIEW

**Comment by franciscoemanuel** [comment]
resolves #2

**Comment by SuddenlyPineapple** [comment]
I think it should be something simpler and your example is missing unit tests :/ The idea is to delete some lines before workshop from implementation and give students half of implementation and task them with making tests come green.

**Comment by franciscoemanuel** [comment]
@SuddenlyPineapple I've updated the example with a simpler one, and added the unit test for the component.

**Review by SuddenlyPineapple — APPROVED** [review]

**Comment by SuddenlyPineapple** [comment]
@franciscoemanuel I've merged this, tell me later if it has give you progress in Hacktoberfest ;)

**Pull request merged**
